#include "../utilities/utilities.h"

#ifndef ATA_INTERNAL_H
#define ATA_INTERNAL_H

// ATA LEGACY REGISTER PRIMARY AND SECONDARY CHANNELS
#define ATA_BASE_REG_1 0x1F0
#define ATA_BASE_REG_2 0x170
#define ATA_REG_CONTROL_1 0x3F6
#define ATA_REG_CONTROL_2 0x376

// ATA CHANNELS
#define ATA_PRIMARY 0
#define ATA_SECONDARY 1

// ATA DRIVES
#define ATA_MASTER 0
#define ATA_SLAVE 1

// ATA LEGACY REGISTER OFFSETS
#define ATA_DATA_OFFSET 0x0
#define ATA_ERR_OFFSET 0x1
#define ATA_SECCOUNT_OFFSET 0x2
#define ATA_LBA0_OFFSET 0x3
#define ATA_LBA1_OFFSET 0x4
#define ATA_LBA2_OFFSET 0x5
#define ATA_HDDEVSEL_OFFSET 0x6
#define ATA_COMMAND_OFFSET 0x7
#define ATA_STATUS_OFFSET 0x7
#define ATA_REG_CONTROL 0x3F6

// ATA STATUS FLAGS
#define ATA_STATUS_ERR 0x01
#define ATA_STATUS_DRQ 0x08
#define ATA_STATUS_SRV 0x10
#define ATA_STATUS_DF 0x20
#define ATA_STATUS_RDY 0x40
#define ATA_STATUS_BSY 0x80

// ATA ERROR FLAGS
#define ATA_ERR_AMNF 0x01
#define ATA_ERR_TK0NF 0x02
#define ATA_ERR_ABRT 0x04
#define ATA_ERR_MCR 0x08   
#define ATA_ERR_IDNF 0x10
#define ATA_ERR_MC 0x20
#define ATA_ERR_UNC 0x40
#define ATA_ERR_BBK 0x80

// ATA COMMANDS
#define ATA_CMD_IDENTIFY 0xEC
#define ATA_CMD_READ_PIO 0x20
#define ATA_CMD_WRITE_PIO 0x30
#define ATA_CMD_CACHE_FLUSH 0xE7

// ATA LBA MODE ENABLE
#define ATA_LBA_MODE 0xE0

// ATA TYPES
#define ATA_TYPE_ATA 0
#define ATA_TYPE_ATAPI 1

// ATA IDENTIFY DEVICE DATA STRUCTURE
#define ATA_IDENTIFY_DATA_SIZE 512
#define ATA_IDENTIFY_DEVICETYPE_OFFSET 0
#define ATA_IDENTIFY_CAPABILITIES_OFFSET 49
#define ATA_IDENTIFY_COMMANDSETS_OFFSET 82
#define ATA_IDENTIFY_SIZE_OFFSET 60
#define ATA_IDENTIFY_MODEL_OFFSET 27

 // Timeout in tries for ATA operations
#define ATA_TIMEOUT 10000

// ATA MEMORY ADDRESSING
#define ATA_DEVICES_RAM_ADDR 0x00091000
#define ATA_DEVICES_COUNT 4
#define ATA_DEVICE_STRUCTURE_SIZE sizeof(ata_device)
#define ATA_DEVICES_SIZE (sizeof(ata_device) * ATA_DEVICES_COUNT)

#endif
